- link:
    ~/.config/i3: i3
    ~/.config/i3blocks/config: i3/i3blocks.conf
    ~/.config/i3blocks/volume-pw: i3/volume-pw
    ~/.profile: shells/profile
    ~/.config/mimeapps.list: mimeapps.list
- shell:
    - chmod +x ~/.config/i3blocks/volume-pw 
